import type { CropInfo } from "@shared/schema";

export const uaeCropCalendar: CropInfo[] = [
  {
    id: "tomato",
    nameEn: "Tomato",
    nameAr: "طماطم",
    plantingMonths: [9, 10, 11],
    harvestMonths: [12, 1, 2, 3],
    category: "Vegetables",
    descriptionEn: "Best grown in cooler months. Requires regular watering and support structures.",
    descriptionAr: "يُزرع بشكل أفضل في الأشهر الباردة. يحتاج إلى الري المنتظم وهياكل الدعم.",
  },
  {
    id: "cucumber",
    nameEn: "Cucumber",
    nameAr: "خيار",
    plantingMonths: [9, 10, 11, 2, 3],
    harvestMonths: [11, 12, 1, 4, 5],
    category: "Vegetables",
    descriptionEn: "Thrives in UAE's warm climate. Needs frequent watering and well-drained soil.",
    descriptionAr: "ينمو بشكل جيد في مناخ الإمارات الدافئ. يحتاج إلى الري المتكرر والتربة جيدة التصريف.",
  },
  {
    id: "eggplant",
    nameEn: "Eggplant",
    nameAr: "باذنجان",
    plantingMonths: [9, 10, 11],
    harvestMonths: [12, 1, 2, 3, 4],
    category: "Vegetables",
    descriptionEn: "Heat-tolerant crop. Plant in autumn for best results in UAE conditions.",
    descriptionAr: "محصول يتحمل الحرارة. يُزرع في الخريف للحصول على أفضل النتائج في ظروف الإمارات.",
  },
  {
    id: "lettuce",
    nameEn: "Lettuce",
    nameAr: "خس",
    plantingMonths: [10, 11, 12, 1],
    harvestMonths: [12, 1, 2, 3],
    category: "Leafy Greens",
    descriptionEn: "Grows well in cooler months. Requires shade during hot periods and consistent moisture.",
    descriptionAr: "ينمو جيداً في الأشهر الباردة. يحتاج إلى الظل خلال الفترات الحارة والرطوبة المستمرة.",
  },
  {
    id: "spinach",
    nameEn: "Spinach",
    nameAr: "سبانخ",
    plantingMonths: [10, 11, 12, 1, 2],
    harvestMonths: [12, 1, 2, 3, 4],
    category: "Leafy Greens",
    descriptionEn: "Ideal winter crop. Fast-growing and nutrient-rich.",
    descriptionAr: "محصول شتوي مثالي. سريع النمو وغني بالمغذيات.",
  },
  {
    id: "carrot",
    nameEn: "Carrot",
    nameAr: "جزر",
    plantingMonths: [10, 11, 12, 1],
    harvestMonths: [1, 2, 3, 4],
    category: "Root Vegetables",
    descriptionEn: "Plant in well-drained sandy soil. Avoid heavy clay soils.",
    descriptionAr: "يُزرع في تربة رملية جيدة التصريف. تجنب التربة الطينية الثقيلة.",
  },
  {
    id: "radish",
    nameEn: "Radish",
    nameAr: "فجل",
    plantingMonths: [10, 11, 12, 1, 2],
    harvestMonths: [11, 12, 1, 2, 3],
    category: "Root Vegetables",
    descriptionEn: "Fast-growing crop, ready in 3-4 weeks. Great for beginners.",
    descriptionAr: "محصول سريع النمو، يكون جاهزاً في 3-4 أسابيع. رائع للمبتدئين.",
  },
  {
    id: "pepper",
    nameEn: "Bell Pepper",
    nameAr: "فلفل حلو",
    plantingMonths: [9, 10, 11, 2],
    harvestMonths: [12, 1, 2, 3, 4, 5],
    category: "Vegetables",
    descriptionEn: "Grows well in UAE climate. Requires full sun and regular watering.",
    descriptionAr: "ينمو جيداً في مناخ الإمارات. يحتاج إلى شمس كاملة وري منتظم.",
  },
  {
    id: "zucchini",
    nameEn: "Zucchini",
    nameAr: "كوسة",
    plantingMonths: [9, 10, 11, 2, 3],
    harvestMonths: [11, 12, 1, 4, 5],
    category: "Vegetables",
    descriptionEn: "Productive crop in UAE. Plant in cooler months for better yield.",
    descriptionAr: "محصول منتج في الإمارات. يُزرع في الأشهر الباردة للحصول على إنتاج أفضل.",
  },
  {
    id: "okra",
    nameEn: "Okra",
    nameAr: "بامية",
    plantingMonths: [3, 4, 5, 6],
    harvestMonths: [5, 6, 7, 8, 9],
    category: "Vegetables",
    descriptionEn: "Heat-loving crop. Perfect for UAE's hot summer months.",
    descriptionAr: "محصول محب للحرارة. مثالي لأشهر الصيف الحارة في الإمارات.",
  },
  {
    id: "date-palm",
    nameEn: "Date Palm",
    nameAr: "نخيل التمر",
    plantingMonths: [2, 3, 4],
    harvestMonths: [8, 9, 10],
    category: "Fruits",
    descriptionEn: "Traditional UAE crop. Extremely heat-tolerant and drought-resistant.",
    descriptionAr: "محصول إماراتي تقليدي. يتحمل الحرارة الشديدة ومقاوم للجفاف.",
  },
  {
    id: "mango",
    nameEn: "Mango",
    nameAr: "مانجو",
    plantingMonths: [3, 4, 5],
    harvestMonths: [6, 7, 8],
    category: "Fruits",
    descriptionEn: "Grows well in UAE's hot climate. Requires deep watering.",
    descriptionAr: "ينمو جيداً في مناخ الإمارات الحار. يحتاج إلى ري عميق.",
  },
  {
    id: "strawberry",
    nameEn: "Strawberry",
    nameAr: "فراولة",
    plantingMonths: [10, 11, 12],
    harvestMonths: [1, 2, 3, 4],
    category: "Fruits",
    descriptionEn: "Winter crop in UAE. Requires cool temperatures and consistent watering.",
    descriptionAr: "محصول شتوي في الإمارات. يحتاج إلى درجات حرارة باردة وري مستمر.",
  },
  {
    id: "watermelon",
    nameEn: "Watermelon",
    nameAr: "بطيخ",
    plantingMonths: [2, 3, 4],
    harvestMonths: [5, 6, 7],
    category: "Fruits",
    descriptionEn: "Summer crop. Needs plenty of space and water.",
    descriptionAr: "محصول صيفي. يحتاج إلى مساحة كبيرة والكثير من الماء.",
  },
  {
    id: "mint",
    nameEn: "Mint",
    nameAr: "نعناع",
    plantingMonths: [9, 10, 11, 2, 3],
    harvestMonths: [11, 12, 1, 2, 3, 4, 5],
    category: "Herbs",
    descriptionEn: "Easy to grow. Prefers partial shade and moist soil.",
    descriptionAr: "سهل الزراعة. يفضل الظل الجزئي والتربة الرطبة.",
  },
  {
    id: "coriander",
    nameEn: "Coriander",
    nameAr: "كزبرة",
    plantingMonths: [10, 11, 12, 1, 2],
    harvestMonths: [12, 1, 2, 3, 4],
    category: "Herbs",
    descriptionEn: "Cool season herb. Quick growing and aromatic.",
    descriptionAr: "عشبة للموسم البارد. سريعة النمو وعطرية.",
  },
  {
    id: "basil",
    nameEn: "Basil",
    nameAr: "ريحان",
    plantingMonths: [3, 4, 5, 9, 10],
    harvestMonths: [5, 6, 7, 11, 12],
    category: "Herbs",
    descriptionEn: "Warm weather herb. Requires full sun and regular harvesting.",
    descriptionAr: "عشبة الطقس الدافئ. تحتاج إلى شمس كاملة وحصاد منتظم.",
  },
  {
    id: "parsley",
    nameEn: "Parsley",
    nameAr: "بقدونس",
    plantingMonths: [10, 11, 12, 1, 2],
    harvestMonths: [12, 1, 2, 3, 4, 5],
    category: "Herbs",
    descriptionEn: "Hardy herb for cooler months. Rich in vitamins.",
    descriptionAr: "عشبة قوية للأشهر الباردة. غنية بالفيتامينات.",
  },
];

export function getCropsByMonth(month: number): CropInfo[] {
  return uaeCropCalendar.filter(crop => 
    crop.plantingMonths.includes(month)
  );
}

export function getCurrentSeasonCrops(): CropInfo[] {
  const currentMonth = new Date().getMonth() + 1;
  return getCropsByMonth(currentMonth);
}

export function getCropById(id: string): CropInfo | undefined {
  return uaeCropCalendar.find(crop => crop.id === id);
}
